#!/bin/sh

runner=`find packages -name nunit3-console.exe`
find Test -name \*.csproj > tests.txt

# tests are one-per-line; make them comma-separated for the test runner
#args=`echo $tests | sed 's/\n/\, /'`

$runner --testlist=tests.txt
#echo $runner --test=$args
# this should work: run all tests at once: $runner --test=$args

#for test in $tests ; do
    #$runner $test
#done


